apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend-workload
  namespace: default
spec:
  container:
    image: registry.openchoreo-workflow-plane.svc.cluster.local:10082/doclet-frontend-image:v1-f3a5cd49
  dependencies:
    endpoints:
    - component: document-svc
      envBindings:
        address: DOC_SERVICE_URL
      name: http
      visibility: project
    - component: collab-svc
      envBindings:
        address: COLLAB_SERVICE_URL
      name: http
      visibility: project
  endpoints:
    http:
      port: 80
      type: HTTP
      visibility:
      - external
  owner:
    componentName: frontend
    projectName: doclet
