global_defs {
    router_id TRUENAS_DNS_BACKUP
    script_user root
    enable_script_security
}

vrrp_script chk_dns {
    script "/bin/sh -c 'nc -z -w2 192.168.0.129 53'"
    interval 5
    weight 0
    fall 3
    rise 2
}

vrrp_instance DNS_VIP {
    state BACKUP
    interface eno1
    virtual_router_id 53
    priority 50
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass HHsiI0T7
    }

    virtual_ipaddress {
        192.168.0.53/24
    }

    track_script {
        chk_dns
    }
}
